# Generated by Django 4.2 on 2025-05-13 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noteapp', '0002_usersignup_pphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('cate', models.CharField(max_length=100)),
                ('notefile', models.FileField(upload_to='Notesfiles')),
                ('desc', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Recjectd')], default='Pending', max_length=10)),
                ('updated_at', models.DateTimeField(blank=True)),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='noteapp.usersignup')),
            ],
        ),
    ]
